import { LineEdit, Switch } from "std-widgets.slint";

export component ArgRowTextWoWidth inherits Text {
    overflow: TextOverflow.clip;
    horizontal-alignment: TextHorizontalAlignment.left;
    vertical-alignment: TextVerticalAlignment.center;
}

export component ArgRowText inherits ArgRowTextWoWidth {
    width: 30%;
}

export component ArgRowTextInput inherits LineEdit {
    in-out property <string> input;

    height: 50px;
    input-type: InputType.text;
    text <=> self.input;
}

export component ArgRowBoolInput inherits Switch {
    in-out property <bool> input;

    height: 50px;
    x: self.width / 2 - 20px;
    checked <=> self.input;
}
