export global CommandLogic {
    in-out property <[string]> commands_list: [];
    in-out property <string> public_key: "";
    in-out property <string> private_pem_path: "";
    in-out property <string> command: "";
    in-out property <string> deadline: "";
    in-out property <string> ntp: "";
    callback add_command(string);
    callback exec_command(string);
    callback del_command(string);
}
