import { Button } from "std-widgets.slint";
import {
    ArgRowText,
    ArgRowTextWoWidth,
    ArgRowTextInput,
    ArgRowBoolInput,
} from "./arg-row.slint";
import { SlintRustBridge } from "slint-rust-bridge.slint";

export component Create inherits VerticalLayout {
    property <string> address: "";
    property <bool> permissive: false;
    property <string> ip: "";
    property <bool> ipv4: false;
    property <bool> ipv6: false;

    Flickable {
        VerticalLayout {
            padding-top: 10px;
            padding-left: 10px;
            padding-right: 10px;

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "server";
                }

                ArgRowTextInput {
                    input <=> root.address;
                }
            }

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "command";
                }

                ArgRowTextInput {
                    input <=> SlintRustBridge.command;
                }
            }

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "ip sent to server";
                }

                ArgRowTextInput {
                    input <=> root.ip;
                }
            }

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "source IP doesn't have\nto match provided IP";
                }

                ArgRowBoolInput {
                    input <=> root.permissive;
                }
            }

            HorizontalLayout {
                height: 50px;
                ArgRowText {
                    text: "use ipv4 only";
                }

                ArgRowBoolInput {
                    input <=> root.ipv4;
                }
            }

            HorizontalLayout {
                height: 50px;
                ArgRowText {
                    text: "use ipv6 only";
                }

                ArgRowBoolInput {
                    input <=> root.ipv6;
                }
            }

            Rectangle {
                vertical-stretch: 2;
            }

            HorizontalLayout {
                Button {
                    height: 50px;
                    text: "Add Command";
                    clicked => {
                        SlintRustBridge.add_command({
                            address: root.address,
                            command: SlintRustBridge.command,
                            permissive: root.permissive,
                            ip: root.ip,
                            ipv4: root.ipv4,
                            ipv6: root.ipv6,
                            name: "",
                            color: #CCCCCC,
                        });
                    }
                }
            }
        }
    }
}
