import { Button } from "std-widgets.slint";
import { ArgRowText, ArgRowTextWoWidth, ArgRowTextInput, ArgRowBoolInput } from "./arg-row.slint";
import { SlintRustBridge } from "slint-rust-bridge.slint";

export component Create inherits VerticalLayout {
    property <string> address: "";
    property <bool> permissive: false;
    property <string> ip: "";
    property <bool> ipv4: false;
    property <bool> ipv6: false;

    Flickable {
        VerticalLayout {
            padding-top: 10px;
            padding-left: 10px;
            padding-right: 10px;

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "address";
                }

                ArgRowTextInput {
                    input <=> root.address;
                }
            }

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "command";
                }

                ArgRowTextInput {
                    input <=> SlintRustBridge.command;
                }
            }

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "deadline";
                }

                ArgRowTextInput {
                    input <=> SlintRustBridge.deadline;
                }
            }

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "ip";
                }

                ArgRowTextInput {
                    input <=> root.ip;
                }
            }

            HorizontalLayout {
                padding-bottom: 10px;
                ArgRowText {
                    text: "ntp";
                }

                ArgRowTextInput {
                    input <=> SlintRustBridge.ntp;
                }
            }

            HorizontalLayout {
                padding-bottom: 10px;
                padding-top: 10px;
                padding-right: 20px;
                alignment: space-between;

                VerticalLayout {
                    height: 50px;
                    ArgRowTextWoWidth {
                        text: "permissive";
                    }

                    ArgRowBoolInput {
                        input <=> root.permissive;
                    }
                }

                VerticalLayout {
                    height: 50px;
                    ArgRowTextWoWidth {
                        text: "ipv4";
                    }

                    ArgRowBoolInput {
                        input <=> root.ipv4;
                    }
                }

                VerticalLayout {
                    height: 50px;
                    ArgRowTextWoWidth {
                        text: "ipv6";
                    }

                    ArgRowBoolInput {
                        input <=> root.ipv6;
                    }
                }
            }

            Rectangle {
                vertical-stretch: 2;
            }

            HorizontalLayout {
                Button {
                    height: 50px;
                    text: "Add Command";
                    clicked => {
                        SlintRustBridge.add_command(
                            "send"//
                            + (root.address == "" ? "" : " --address " + root.address)//
                            + (SlintRustBridge.command == "" ? "" : " --command " + SlintRustBridge.command)//
                            + " --deadline " + SlintRustBridge.deadline//
                            + (root.permissive ? "--permissive" : "")//
                            + (root.ip == "" ? "" : " --ip " + root.ip)//
                            + (SlintRustBridge.ntp == "" ? "" : " --ntp " + SlintRustBridge.ntp)//
                            + (root.ipv4 ? " --ipv4" : "")//
                            + (root.ipv6 ? " --ipv6" : "")//
                        )
                    }
                }
            }
        }
    }
}
