import { Button, TextEdit, LineEdit, ScrollView } from "std-widgets.slint";
import { SlintRustBridge } from "slint-rust-bridge.slint";

export component Dashboard inherits VerticalLayout {
    property <bool> show_key: false;
    alignment: start;
    spacing: 0px;
    padding: 0px;

    VerticalLayout {
        spacing: 10px;
        padding-top: 10px;
        padding-left: 10px;
        padding-right: 10px;
        height: 45%;

        commands_config_box := TextEdit {
            font-size: 12px;
            enabled: false;
            wrap: word-wrap;
            has-focus: false;
            text <=> SlintRustBridge.commands_config;
        }

        HorizontalLayout {
            spacing: 10px;

            Button {
                height: 50px;
                text: "Rst";
                clicked => {
                    SlintRustBridge.reset_commands_config();
                }
            }

            Button {
                height: 50px;
                text: "💾";
                clicked => {
                    SlintRustBridge.set_commands_config(SlintRustBridge.commands_config);
                }
            }

            Button {
                height: 50px;
                text: "📋";
                clicked => {
                    commands_config_box.select-all();
                    commands_config_box.copy();
                    commands_config_box.clear-selection();
                }
            }

            Button {
                height: 50px;
                text: "📥";
                clicked => {
                    commands_config_box.text = "";
                    commands_config_box.paste();
                }
            }
        }
    }

    VerticalLayout {
        spacing: 10px;
        padding-top: 10px;
        padding-left: 10px;
        padding-right: 10px;
        height: 5%;
        alignment: center;

        Rectangle {
            width: 100%;
            height: 1px;
            background: lightgray;
        }
    }

    VerticalLayout {
        alignment: start;
        spacing: 10px;
        padding-top: 10px;
        padding-left: 10px;
        padding-right: 10px;
        height: 25%;

        HorizontalLayout {
            spacing: 10px;

            Text {
                font-size: 12px;
                vertical-alignment: center;
                text: "AES Key:";
            }

            key_box := LineEdit {
                placeholder-text: "Generate or paste your key here - use the buttons below";
                input-type: root.show_key ? text : password;
                font-size: 12px;
                enabled: false;
                text <=> SlintRustBridge.key;
            }
        }

        HorizontalLayout {
            spacing: 10px;

            Button {
                height: 50px;
                text: "Gen";
                clicked => {
                    key_box.text = SlintRustBridge.generate_key();
                }
            }

            Button {
                height: 50px;
                text: root.show_key ? "🔒" : "🔓";
                clicked => {
                    root.show_key = !root.show_key;
                }
            }

            Button {
                height: 50px;
                text: "📋";
                clicked => {
                    key_box.select-all();
                    key_box.copy();
                    key_box.clear-selection();
                }
            }

            Button {
                height: 50px;
                text: "📥";
                clicked => {
                    key_box.text = "";
                    key_box.paste();
                }
            }
        }
    }

    VerticalLayout {
        height: 25%;
        alignment: end;

        Button {
            height: 50px;
            text: "Update Application";
            clicked => {
                SlintRustBridge.update_application();
            }
        }
    }
}
