import { Button, TextEdit, ScrollView } from "std-widgets.slint";
import { SlintRustBridge } from "slint-rust-bridge.slint";

export component Dashboard inherits VerticalLayout {
    padding-top: 10px;
    padding-left: 10px;
    padding-right: 10px;

    commands_config_box := TextEdit {
        font-size: 9px;
        enabled: false;
        wrap: word-wrap;
        has-focus: false;
        text <=> SlintRustBridge.commands_config;
    }

    Rectangle {
        height: 10px;
    }

    Button {
        height: 50px;
        text: "Save Commands";
        clicked => {
            SlintRustBridge.set_commands_config(SlintRustBridge.commands_config);
        }
    }

    Rectangle {
        height: 10px;
    }

    Button {
        height: 50px;
        text: "Copy Commands";
        clicked => {
            commands_config_box.select-all();
            commands_config_box.copy();
            commands_config_box.clear-selection()
        }
    }

    Rectangle {
        height: 10px;
    }

    Button {
        height: 50px;
        text: "Paste Commands";
        clicked => {
            commands_config_box.text = "";
            commands_config_box.paste();
        }
    }

    Rectangle {
        height: 10px;
    }

    Button {
        height: 50px;
        text: "Reset Commands";
        clicked => {
            SlintRustBridge.reset_commands_config();
        }
    }

    Rectangle {
        height: 10px;
    }

    Button {
        height: 50px;
        text: "Update Application";
        clicked => {
            SlintRustBridge.update_application();
        }
    }

    Rectangle {
        height: 10px;
    }

    key_box := TextEdit {
        visible: false;
        enabled: false;
        width: 0;
        height: 0;
        has-focus: false;
        text <=> SlintRustBridge.key;
    }

    Button {
        height: 50px;
        text: "Generate Key";
        clicked => {
            key_box.text = SlintRustBridge.generate_key()
        }
    }

    Button {
        height: 50px;
        text: "Copy Key";
        clicked => {
            key_box.select-all();
            key_box.copy();
            key_box.clear-selection()
        }
    }

    Button {
        height: 50px;
        text: "Paste Key";
        clicked => {
            key_box.text = "";
            key_box.paste();
        }
    }
}
