import { Button, ListView } from "std-widgets.slint";
import { CommandLogic } from "command-logic.slint";

export component Execute inherits VerticalLayout {
    ListView {

        for data[i] in CommandLogic.commands_list: HorizontalLayout {
            padding-top: 10px;
            padding-bottom: 10px;

            Rectangle {
                border-color: #1976d2;
                border-width: 2px;
                border-radius: 5px;
                height: 50px;
                width: 50px;
                Button {
                    height: 48px;
                    width: 48px;
                    text: "▶";
                    clicked => {
                        CommandLogic.exec_command(data.command, i);
                    }
                }
            }

            Rectangle {
                horizontal-stretch: 1.0;
                border-color: data.color;
                border-width: 2px;
                border-radius: 5px;
                Text {
                    x: 5px;
                    font-size: 12px;
                    width: parent.width - self.x - 5px;
                    height: 50px;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    text: data.name;
                    wrap: word-wrap;
                }
            }

            Rectangle {
                border-color: #d32f2f;
                border-width: 2px;
                border-radius: 5px;
                height: 50px;
                width: 50px;
                Button {
                    height: 48px;
                    width: 48px;
                    text: "🗑";
                    clicked => {
                        CommandLogic.del_command(data.command, i)
                    }
                }
            }
        }
    }
}
