struct CommandData {
    address: string,
    command: string,
    deadline: string,
    permissive: bool,
    ip: string,
    ntp: string,
    ipv4: bool,
    ipv6: bool,
    name: string,
    color: color,
}
export global SlintRustBridge {
    // used in "Dashboard" tab to show the current configuration file
    in-out property <string> commands_config: "";  // the contents of the configuration file

    callback set_commands_config(string);
    callback reset_commands_config();
    callback update_application();
    callback generate_key() -> string;

    // used in "Create" tab to create a new command for later execution
    in-out property <string> command: "";
    in-out property <string> deadline: "";
    in-out property <string> ntp: "";

    callback add_command(CommandData);

    // used in "Execute" tab to execute a command
    in-out property <string> key: "";
    in-out property <[CommandData]> commands_list: [];

    callback exec_command(CommandData, string);
    callback del_command(CommandData);
}
