# MANDATORY - public IP address of your server where this service runs on
ips = ["127.0.0.1", "dead:beef:dead:beef:dead:beef:dead:beef"]
address = "[::]:8080"        # OPTIONAL  - address the ruroco serer listens on, if systemd/ruroco.socket is not used
config_dir = "/etc/ruroco/"  # OPTIONAL  - path where the configuration files (.pem and others) are saved
ntp = "system"               # OPTIONAL  - NTP server configuration - use "system" to use the systems time configuration
socket_user = "ruroco"       # OPTIONAL  - user of socket, facilitating communication between server and commander
socket_group = "ruroco"      # OPTIONAL  - user group of socket, facilitating communication between server and commander

[commands]                   # MANDATORY - but can be empty
open_ssh = "ufw allow from $RUROCO_IP proto tcp to any port 22"         #  open ssh for IP where request came from
close_ssh = "ufw delete allow from $RUROCO_IP proto tcp to any port 22" # close ssh for IP where request came from
